services:
  - type: web
    name: todolist-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: MONGO_URI
        # 这个值需要在Render部署时手动设置，不应在代码仓库中包含实际凭证
        value: MONGODB_URI_FROM_RENDER_DASHBOARD
      - key: PORT
        value: 3000
